version: "3.9"
services:
  backend:
    build: .
    command: sh -c "
      sleep 4 &&
      ./bin/kvs"
    environment:
      - PORT=8080
      - TTL=10
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=kvs
      - POSTGRES_PASS=password
      - POSTGRES_DB=kvs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: kvs
      POSTGRES_DB: kvs
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"