apiVersion: v1
kind: Service
metadata:
  name: kvs-postgres
spec:
  selector:
    app: kvs-postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvs-postgres
spec:
  selector:
    matchLabels:
      app: kvs-postgres
  template:
    metadata:
      labels:
        app: kvs-postgres
    spec:
      volumes:
        - name: kvs-postgres-pvc
          persistentVolumeClaim:
            claimName: kvs-postgres-pvc
      containers:
        - name: kvs-postgres
          image: postgres
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: postgres.user
                  name: kvs
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres.pass
                  name: kvs
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: postgres.db
                  name: kvs
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: kvs-postgres-pvc
              mountPath: /var/lib/postgresql/data
              subPath: kvs/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kvs-postgres-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kvs-postgres-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /mnt/storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - silverstone
