apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pod
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pod
    spec:
      containers:
        - name: kvs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: TTL
              valueFrom:
                configMapKeyRef:
                  key: ttl 
                  name: {{ .Release.Name }}-configmap
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: {{ .Release.Name }}-configmap
            {{- if .Values.sqlite }}
            - name: SQLITE_DB
              valueFrom:
                configMapKeyRef:
                  key: sqlite.db
                  name: {{ .Release.Name }}-configmap
            {{- end}}
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: postgres.host
                  name: {{ .Release.Name }}-configmap
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: postgres.port
                  name: {{ .Release.Name }}-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: postgres.user
                  name: {{ .Release.Name }}-configmap
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  key: postgres.pass
                  name: {{ .Release.Name }}-secret
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: postgres.db
                  name: {{ .Release.Name }}-configmap
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: redis.host
                  name: {{ .Release.Name }}-configmap
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: redis.port
                  name: {{ .Release.Name }}-configmap
          ports:
            - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
