apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  port: {{ .Values.service.port | quote }}
  ttl: {{ .Values.cache.ttl | quote }}
  postgres.host: {{ .Release.Name }}-postgres-service
  postgres.port: {{ .Values.database.port | quote }}
  postgres.user: {{ .Values.database.user }}
  postgres.db: {{ .Values.database.db }}
  redis.host: {{ .Values.cache.host }}
  redis.port: {{ .Values.cache.port | quote}}
  {{ - if .Values.sqlite }}
  sqlite.db: {{ .Values.sqlite }}
  {{ - end }}