apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  port: {{ .Values.service.port | quote }}
  ttl: {{ .Values.cache.ttl | quote }}
  postgres.host: {{ .Release.Name }}-postgres-service
  postgres.port: {{ .Values.database.port | quote }}
  postgres.user: {{ .Values.database.user }}
  postgres.db: {{ .Values.database.db }}
  redis.host: {{ .Release.Name }}-redis-service
  redis.port: "6379"