apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis-pod
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
